"""initial_schema — authoritative baseline built from the ORM models.

This baseline creates the entire current schema from SQLAlchemy metadata.

Why a create_all baseline (rather than per-table DDL): the previous migration
chain was non-functional — early revisions ran ALTER TABLE / add_column against
tables that did not yet exist on a fresh database, so the chain failed and the
app fell back to Base.metadata.create_all() at startup. The models have always
been the real source of truth. This squashes that reality into a single,
deterministic migration so Alembic — not a startup create_all — owns the schema.

To evolve the schema from here, use autogenerated revisions:
    alembic revision --autogenerate -m "describe change"
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69da4343ec10"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _metadata():
    """Import every model module so all tables register on Base.metadata."""
    from backend.database import Base
    import backend.models  # noqa: F401 — core + phase2 + advanced + agent/system tables

    try:
        from backend.models import phase2b_models  # noqa: F401
    except Exception:
        pass
    try:
        from backend.models import phase3_models  # noqa: F401
    except Exception:
        pass
    return Base.metadata


def upgrade() -> None:
    _metadata().create_all(bind=op.get_bind())


def downgrade() -> None:
    # Drop every application table with CASCADE (handles FK cycles and the
    # unnamed use_alter foreign keys that metadata.drop_all() cannot emit).
    # alembic_version is preserved so Alembic can record the downgrade.
    op.get_bind().execute(
        sa.text(
            """
            DO $$
            DECLARE r RECORD;
            BEGIN
                FOR r IN (
                    SELECT tablename FROM pg_tables
                    WHERE schemaname = 'public' AND tablename <> 'alembic_version'
                ) LOOP
                    EXECUTE 'DROP TABLE IF EXISTS public.' || quote_ident(r.tablename) || ' CASCADE';
                END LOOP;
            END $$;
            """
        )
    )
