"""add_tier2_models_and_columns

Revision ID: a0320c41e922
Revises: 69da4343ec10
Create Date: 2026-02-16 18:41:15.731322
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0320c41e922'
down_revision: Union[str, None] = '69da4343ec10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('copilot_conversations', sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_copilot_conversations_session_id'), table_name='copilot_conversations')
    op.create_index(op.f('ix_copilot_conversations_session_id'), 'copilot_conversations', ['session_id'], unique=True)
    op.add_column('threat_intel_entries', sa.Column('intel_type', sa.String(length=100), nullable=True))
    op.add_column('threat_intel_entries', sa.Column('location_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('threat_intel_entries', sa.Column('threshold_adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('threat_intel_entries', sa.Column('impact_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('threat_intel_entries', sa.Column('priority', sa.Integer(), server_default='5', nullable=False))
    op.add_column('threat_intel_entries', sa.Column('source_url', sa.String(length=1024), nullable=True))
    op.add_column('threat_intel_entries', sa.Column('processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('threat_intel_entries', sa.Column('agent_acknowledgments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threat_intel_entries', 'agent_acknowledgments')
    op.drop_column('threat_intel_entries', 'processed')
    op.drop_column('threat_intel_entries', 'source_url')
    op.drop_column('threat_intel_entries', 'priority')
    op.drop_column('threat_intel_entries', 'impact_zones')
    op.drop_column('threat_intel_entries', 'threshold_adjustments')
    op.drop_column('threat_intel_entries', 'location_context')
    op.drop_column('threat_intel_entries', 'intel_type')
    op.drop_index(op.f('ix_copilot_conversations_session_id'), table_name='copilot_conversations')
    op.create_index(op.f('ix_copilot_conversations_session_id'), 'copilot_conversations', ['session_id'], unique=False)
    op.drop_column('copilot_conversations', 'messages')
    # ### end Alembic commands ###
